name: Build wgrib2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install GCC and gfortran
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y gcc gfortran
        sudo apt-get install -y wgrib2
        
    - name: Clone wgrib2 repository
      run: git clone https://github.com/weathersource/wgrib2
      
    - name: Build wgrib2
      run: |
        export FC=gfortran
        export CC=gcc
        export COMP_SYS=gnu_linux
        cd wgrib2
        make
